"""Add telemetry_records table

Revision ID: 03245e76bd40
Revises: '949dfc0a8c86'
Create Date: 2026-07-23 11:34:41.141897

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "03245e76bd40"
down_revision: str | None = "949dfc0a8c86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_records",
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization ownership foreign key",
        ),
        sa.Column(
            "device_id", sa.Uuid(), nullable=False, comment="Device that produced the telemetry"
        ),
        sa.Column(
            "device_assignment_id",
            sa.Uuid(),
            nullable=True,
            comment="Resolved device assignment at time of packet",
        ),
        sa.Column(
            "trip_id",
            sa.Uuid(),
            nullable=True,
            comment="Resolved active/finalizing trip at time of packet",
        ),
        sa.Column(
            "source_type",
            sa.String(length=20),
            server_default="HARDWARE",
            nullable=False,
            comment="Telemetry source (HARDWARE, SIMULATOR, REPLAY)",
        ),
        sa.Column(
            "schema_version",
            sa.String(length=20),
            server_default="1.0",
            nullable=False,
            comment="Telemetry payload schema version",
        ),
        sa.Column(
            "boot_id",
            sa.String(length=100),
            nullable=False,
            comment="Device boot instance identifier",
        ),
        sa.Column(
            "sequence_number",
            sa.BigInteger(),
            nullable=False,
            comment="Monotonically increasing sequence number per boot",
        ),
        sa.Column(
            "device_timestamp",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp reported by device clock",
        ),
        sa.Column(
            "server_received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when server received packet",
        ),
        sa.Column("latitude", sa.Float(), nullable=True, comment="GPS latitude in decimal degrees"),
        sa.Column(
            "longitude", sa.Float(), nullable=True, comment="GPS longitude in decimal degrees"
        ),
        sa.Column(
            "gps_valid",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Flag indicating valid GPS fix",
        ),
        sa.Column(
            "sensor_valid",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Flag indicating valid IMU/sensor readings",
        ),
        sa.Column("speed_kmh", sa.Float(), nullable=True, comment="GPS speed in km/h"),
        sa.Column(
            "forward_acceleration_ms2",
            sa.Float(),
            nullable=True,
            comment="Forward acceleration in m/s^2",
        ),
        sa.Column(
            "lateral_acceleration_ms2",
            sa.Float(),
            nullable=True,
            comment="Lateral acceleration in m/s^2",
        ),
        sa.Column(
            "yaw_rate_deg_s", sa.Float(), nullable=True, comment="Yaw rate in degrees per second"
        ),
        sa.Column(
            "processing_status",
            sa.String(length=30),
            server_default="RECEIVED",
            nullable=False,
            comment="Telemetry packet processing status",
        ),
        sa.Column(
            "validation_status",
            sa.String(length=50),
            nullable=True,
            comment="Validation outcome label",
        ),
        sa.Column(
            "processing_attempts",
            sa.Integer(),
            server_default="1",
            nullable=False,
            comment="Number of processing attempts",
        ),
        sa.Column(
            "last_processing_error",
            sa.String(length=500),
            nullable=True,
            comment="Error message if processing failed",
        ),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when processing finished",
        ),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Original unparsed JSON payload",
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "processing_status IN ("
            "'RECEIVED', 'PROCESSED', 'PARTIAL', 'FAILED', 'DUPLICATE', 'REJECTED'"
            ")",
            name=op.f("ck_telemetry_records_processing_status"),
        ),
        sa.CheckConstraint(
            "source_type IN ('HARDWARE', 'SIMULATOR', 'REPLAY')",
            name=op.f("ck_telemetry_records_source_type"),
        ),
        sa.ForeignKeyConstraint(
            ["device_assignment_id"],
            ["device_assignments.id"],
            name=op.f("fk_telemetry_records_device_assignment_id_device_assignments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_telemetry_records_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_telemetry_records_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_telemetry_records_trip_id_trips"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_records")),
        sa.UniqueConstraint(
            "device_id", "boot_id", "sequence_number", name="uq_telemetry_records_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_telemetry_records_device_assignment_id"),
        "telemetry_records",
        ["device_assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_records_device_id"), "telemetry_records", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_records_organization_id"),
        "telemetry_records",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_records_processing_status"),
        "telemetry_records",
        ["processing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_records_server_received_at"),
        "telemetry_records",
        ["server_received_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_records_trip_id"), "telemetry_records", ["trip_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telemetry_records_trip_id"), table_name="telemetry_records")
    op.drop_index(op.f("ix_telemetry_records_server_received_at"), table_name="telemetry_records")
    op.drop_index(op.f("ix_telemetry_records_processing_status"), table_name="telemetry_records")
    op.drop_index(op.f("ix_telemetry_records_organization_id"), table_name="telemetry_records")
    op.drop_index(op.f("ix_telemetry_records_device_id"), table_name="telemetry_records")
    op.drop_index(op.f("ix_telemetry_records_device_assignment_id"), table_name="telemetry_records")
    op.drop_table("telemetry_records")
    # ### end Alembic commands ###
