"""Add users table

Revision ID: 03703bcbb2ec
Revises: '08fb105ab208'
Create Date: 2026-07-23 11:03:01.943060

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03703bcbb2ec"
down_revision: str | None = "08fb105ab208"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization ownership foreign key",
        ),
        sa.Column(
            "email", sa.String(length=255), nullable=False, comment="Unique login email address"
        ),
        sa.Column(
            "password_hash", sa.String(length=255), nullable=False, comment="Hashed user password"
        ),
        sa.Column(
            "full_name",
            sa.String(length=200),
            nullable=False,
            comment="Full display name of the user",
        ),
        sa.Column(
            "role",
            sa.String(length=30),
            server_default="FLEET_MANAGER",
            nullable=False,
            comment="User role (ADMIN or FLEET_MANAGER)",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="ACTIVE",
            nullable=False,
            comment="Current user status (ACTIVE or DISABLED)",
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of last successful login",
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('ADMIN', 'FLEET_MANAGER')", name=op.f("ck_users_role")),
        sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name=op.f("ck_users_status")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
