"""Add organizations table

Revision ID: 08fb105ab208
Revises: None
Create Date: 2026-07-23 10:53:18.711465

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08fb105ab208"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column(
            "organization_code",
            sa.String(length=50),
            nullable=False,
            comment="Short unique business identifier",
        ),
        sa.Column(
            "name",
            sa.String(length=200),
            nullable=False,
            comment="Display name of the organization",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="ACTIVE",
            nullable=False,
            comment="Current organization status",
        ),
        sa.Column(
            "timezone",
            sa.String(length=50),
            server_default="UTC",
            nullable=False,
            comment="IANA timezone identifier",
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'SUSPENDED', 'INACTIVE')", name=op.f("ck_organizations_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        op.f("ix_organizations_organization_code"),
        "organizations",
        ["organization_code"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_organizations_organization_code"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
