"""add_driving_event_and_scoring_schema

Revision ID: 79e061e2c344
Revises: '03245e76bd40'
Create Date: 2026-07-23 12:18:05.693030

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79e061e2c344"
down_revision: str | None = "03245e76bd40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rule_sets",
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization ownership foreign key",
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Rule set display name"),
        sa.Column(
            "description",
            sa.String(length=255),
            nullable=True,
            comment="Optional rule set description",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="ACTIVE",
            nullable=False,
            comment="Rule set status",
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_rule_sets_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_sets")),
    )
    op.create_index(
        op.f("ix_rule_sets_organization_id"), "rule_sets", ["organization_id"], unique=False
    )
    op.create_table(
        "rule_set_versions",
        sa.Column("rule_set_id", sa.Uuid(), nullable=False, comment="Parent rule set foreign key"),
        sa.Column(
            "version_number",
            sa.Integer(),
            nullable=False,
            comment="Monotonically increasing version index",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="DRAFT",
            nullable=False,
            comment="Version lifecycle status (DRAFT, ACTIVE, RETIRED)",
        ),
        sa.Column(
            "effective_from",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when version becomes effective",
        ),
        sa.Column(
            "activated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when version was activated",
        ),
        sa.Column(
            "activated_by_user_id",
            sa.Uuid(),
            nullable=True,
            comment="User who activated this version",
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ACTIVE', 'RETIRED')", name=op.f("ck_rule_set_versions_status")
        ),
        sa.ForeignKeyConstraint(
            ["activated_by_user_id"],
            ["users.id"],
            name=op.f("fk_rule_set_versions_activated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rule_set_id"],
            ["rule_sets.id"],
            name=op.f("fk_rule_set_versions_rule_set_id_rule_sets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_set_versions")),
        sa.UniqueConstraint(
            "rule_set_id", "version_number", name="uq_rule_set_versions_rule_set_version"
        ),
    )
    op.create_index(
        op.f("ix_rule_set_versions_rule_set_id"), "rule_set_versions", ["rule_set_id"], unique=False
    )
    op.create_table(
        "acceleration_rules",
        sa.Column("rule_set_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "behaviour_type",
            sa.String(length=30),
            nullable=False,
            comment="HARSH_BRAKING or SUDDEN_ACCELERATION",
        ),
        sa.Column(
            "trigger_threshold_ms2",
            sa.Float(),
            nullable=False,
            comment="Acceleration magnitude threshold in m/s^2",
        ),
        sa.Column(
            "release_threshold_ms2",
            sa.Float(),
            nullable=False,
            comment="Acceleration hysteresis release threshold in m/s^2",
        ),
        sa.Column(
            "minimum_duration_ms",
            sa.Integer(),
            server_default="500",
            nullable=False,
            comment="Minimum duration in milliseconds required to confirm event",
        ),
        sa.Column(
            "minimum_speed_kmh",
            sa.Float(),
            server_default="5.0",
            nullable=False,
            comment="Minimum vehicle speed in km/h for rule evaluation",
        ),
        sa.Column(
            "cooldown_ms",
            sa.Integer(),
            server_default="1000",
            nullable=False,
            comment="Cooldown window after event in milliseconds",
        ),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "behaviour_type IN ('HARSH_BRAKING', 'SUDDEN_ACCELERATION')",
            name=op.f("ck_acceleration_rules_behaviour_type"),
        ),
        sa.ForeignKeyConstraint(
            ["rule_set_version_id"],
            ["rule_set_versions.id"],
            name=op.f("fk_acceleration_rules_rule_set_version_id_rule_set_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acceleration_rules")),
    )
    op.create_index(
        op.f("ix_acceleration_rules_rule_set_version_id"),
        "acceleration_rules",
        ["rule_set_version_id"],
        unique=False,
    )
    op.create_table(
        "event_penalties",
        sa.Column("rule_set_version_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column(
            "points_delta", sa.Float(), nullable=False, comment="Negative score point deduction"
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "severity IN ('LOW', 'MODERATE', 'HIGH', 'CRITICAL')",
            name=op.f("ck_event_penalties_severity"),
        ),
        sa.ForeignKeyConstraint(
            ["rule_set_version_id"],
            ["rule_set_versions.id"],
            name=op.f("fk_event_penalties_rule_set_version_id_rule_set_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_penalties")),
        sa.UniqueConstraint(
            "rule_set_version_id",
            "event_type",
            "severity",
            name="uq_event_penalties_version_type_severity",
        ),
    )
    op.create_index(
        op.f("ix_event_penalties_rule_set_version_id"),
        "event_penalties",
        ["rule_set_version_id"],
        unique=False,
    )
    op.create_table(
        "event_severity_bands",
        sa.Column("rule_set_version_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("minimum_measure", sa.Float(), nullable=False),
        sa.Column("maximum_measure", sa.Float(), nullable=True),
        sa.Column("minimum_duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("priority_order", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "severity IN ('LOW', 'MODERATE', 'HIGH', 'CRITICAL')",
            name=op.f("ck_event_severity_bands_severity"),
        ),
        sa.ForeignKeyConstraint(
            ["rule_set_version_id"],
            ["rule_set_versions.id"],
            name=op.f("fk_event_severity_bands_rule_set_version_id_rule_set_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_severity_bands")),
    )
    op.create_index(
        op.f("ix_event_severity_bands_rule_set_version_id"),
        "event_severity_bands",
        ["rule_set_version_id"],
        unique=False,
    )
    op.create_table(
        "overspeed_rules",
        sa.Column("rule_set_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tolerance_kmh",
            sa.Float(),
            server_default="5.0",
            nullable=False,
            comment="Speed limit buffer / tolerance in km/h",
        ),
        sa.Column(
            "minimum_duration_ms",
            sa.Integer(),
            server_default="3000",
            nullable=False,
            comment="Minimum sustained overspeed duration in milliseconds",
        ),
        sa.Column(
            "release_margin_kmh",
            sa.Float(),
            server_default="2.0",
            nullable=False,
            comment="Hysteresis margin below trigger speed for event release",
        ),
        sa.Column(
            "cooldown_ms",
            sa.Integer(),
            server_default="2000",
            nullable=False,
            comment="Cooldown period after event release",
        ),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_set_version_id"],
            ["rule_set_versions.id"],
            name=op.f("fk_overspeed_rules_rule_set_version_id_rule_set_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_overspeed_rules")),
    )
    op.create_index(
        op.f("ix_overspeed_rules_rule_set_version_id"),
        "overspeed_rules",
        ["rule_set_version_id"],
        unique=False,
    )
    op.create_table(
        "risk_bands",
        sa.Column("rule_set_version_id", sa.Uuid(), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("minimum_score", sa.Float(), nullable=False),
        sa.Column("maximum_score", sa.Float(), nullable=False),
        sa.Column("priority_order", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "risk_level IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f("ck_risk_bands_risk_level")
        ),
        sa.ForeignKeyConstraint(
            ["rule_set_version_id"],
            ["rule_set_versions.id"],
            name=op.f("fk_risk_bands_rule_set_version_id_rule_set_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_bands")),
    )
    op.create_index(
        op.f("ix_risk_bands_rule_set_version_id"),
        "risk_bands",
        ["rule_set_version_id"],
        unique=False,
    )
    op.create_table(
        "turning_rules",
        sa.Column("rule_set_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "lateral_acceleration_threshold_ms2",
            sa.Float(),
            nullable=False,
            comment="Lateral acceleration threshold in m/s^2",
        ),
        sa.Column(
            "yaw_rate_threshold_deg_s",
            sa.Float(),
            nullable=False,
            comment="Yaw rate threshold in deg/s",
        ),
        sa.Column(
            "minimum_speed_kmh",
            sa.Float(),
            server_default="10.0",
            nullable=False,
            comment="Minimum speed for sharp turn detection",
        ),
        sa.Column(
            "minimum_duration_ms",
            sa.Integer(),
            server_default="500",
            nullable=False,
            comment="Minimum duration in milliseconds",
        ),
        sa.Column(
            "release_lateral_threshold_ms2",
            sa.Float(),
            nullable=False,
            comment="Hysteresis release lateral accel threshold",
        ),
        sa.Column(
            "release_yaw_threshold_deg_s",
            sa.Float(),
            nullable=False,
            comment="Hysteresis release yaw rate threshold",
        ),
        sa.Column(
            "cooldown_ms",
            sa.Integer(),
            server_default="1000",
            nullable=False,
            comment="Cooldown duration",
        ),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_set_version_id"],
            ["rule_set_versions.id"],
            name=op.f("fk_turning_rules_rule_set_version_id_rule_set_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turning_rules")),
    )
    op.create_index(
        op.f("ix_turning_rules_rule_set_version_id"),
        "turning_rules",
        ["rule_set_version_id"],
        unique=False,
    )
    op.create_table(
        "driving_events",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="ACTIVE", nullable=False),
        sa.Column("severity", sa.String(length=20), server_default="MODERATE", nullable=False),
        sa.Column("source", sa.String(length=30), server_default="BACKEND_RULE", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("rule_set_version_id", sa.Uuid(), nullable=True),
        sa.Column("detection_rule_id", sa.String(length=100), nullable=True),
        sa.Column(
            "primary_measurement",
            sa.Float(),
            nullable=False,
            comment="Peak measurement value (e.g. peak m/s^2 or peak km/h excess)",
        ),
        sa.Column(
            "threshold_value", sa.Float(), nullable=False, comment="Trigger threshold value applied"
        ),
        sa.Column(
            "release_threshold_value",
            sa.Float(),
            nullable=True,
            comment="Hysteresis release threshold applied",
        ),
        sa.Column("maximum_speed_kmh", sa.Float(), nullable=True),
        sa.Column("minimum_forward_acceleration_ms2", sa.Float(), nullable=True),
        sa.Column("maximum_forward_acceleration_ms2", sa.Float(), nullable=True),
        sa.Column("maximum_lateral_acceleration_ms2", sa.Float(), nullable=True),
        sa.Column("maximum_absolute_yaw_rate_deg_s", sa.Float(), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("void_reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ("
            "'HARSH_BRAKING', 'SUDDEN_ACCELERATION', 'OVERSPEEDING', 'SHARP_TURNING'"
            ")",
            name=op.f("ck_driving_events_event_type"),
        ),
        sa.CheckConstraint(
            "severity IN ('LOW', 'MODERATE', 'HIGH', 'CRITICAL')",
            name=op.f("ck_driving_events_severity"),
        ),
        sa.CheckConstraint(
            "source IN ('BACKEND_RULE', 'MANUAL_REVIEW')", name=op.f("ck_driving_events_source")
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'COMPLETED', 'VOIDED')", name=op.f("ck_driving_events_status")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_driving_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_set_version_id"],
            ["rule_set_versions.id"],
            name=op.f("fk_driving_events_rule_set_version_id_rule_set_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_driving_events_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_user_id"],
            ["users.id"],
            name=op.f("fk_driving_events_voided_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_driving_events")),
    )
    op.create_index(
        op.f("ix_driving_events_event_type"), "driving_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_driving_events_organization_id"),
        "driving_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_driving_events_severity"), "driving_events", ["severity"], unique=False
    )
    op.create_index(
        op.f("ix_driving_events_started_at"), "driving_events", ["started_at"], unique=False
    )
    op.create_index(op.f("ix_driving_events_status"), "driving_events", ["status"], unique=False)
    op.create_index(op.f("ix_driving_events_trip_id"), "driving_events", ["trip_id"], unique=False)
    op.create_table(
        "event_detection_states",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=20), server_default="NORMAL", nullable=False),
        sa.Column("candidate_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_event_id", sa.Uuid(), nullable=True),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cooldown_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_telemetry_id", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "state IN ('NORMAL', 'CANDIDATE', 'ACTIVE', 'COOLDOWN')",
            name=op.f("ck_event_detection_states_state"),
        ),
        sa.ForeignKeyConstraint(
            ["active_event_id"],
            ["driving_events.id"],
            name=op.f("fk_event_detection_states_active_event_id_driving_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["latest_telemetry_id"],
            ["telemetry_records.id"],
            name=op.f("fk_event_detection_states_latest_telemetry_id_telemetry_records"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_event_detection_states_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_detection_states")),
        sa.UniqueConstraint(
            "trip_id", "event_type", name="uq_event_detection_states_trip_event_type"
        ),
    )
    op.create_index(
        op.f("ix_event_detection_states_trip_id"),
        "event_detection_states",
        ["trip_id"],
        unique=False,
    )
    op.create_table(
        "event_telemetry_links",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("telemetry_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_role", sa.String(length=20), server_default="DURING", nullable=False),
        sa.Column("sequence_order", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "evidence_role IN ('BEFORE', 'TRIGGER', 'PEAK', 'DURING', 'RELEASE', 'AFTER')",
            name=op.f("ck_event_telemetry_links_evidence_role"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["driving_events.id"],
            name=op.f("fk_event_telemetry_links_event_id_driving_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["telemetry_id"],
            ["telemetry_records.id"],
            name=op.f("fk_event_telemetry_links_telemetry_id_telemetry_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_telemetry_links")),
        sa.UniqueConstraint(
            "event_id", "telemetry_id", name="uq_event_telemetry_links_event_telemetry"
        ),
    )
    op.create_index(
        op.f("ix_event_telemetry_links_event_id"),
        "event_telemetry_links",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_telemetry_links_telemetry_id"),
        "event_telemetry_links",
        ["telemetry_id"],
        unique=False,
    )
    op.create_table(
        "trip_score_ledger",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column(
            "entry_type", sa.String(length=30), server_default="EVENT_PENALTY", nullable=False
        ),
        sa.Column("source_event_id", sa.Uuid(), nullable=True),
        sa.Column("source_pattern_id", sa.String(length=100), nullable=True),
        sa.Column("reverses_entry_id", sa.Uuid(), nullable=True),
        sa.Column("rule_set_version_id", sa.Uuid(), nullable=True),
        sa.Column("penalty_rule_id", sa.String(length=100), nullable=True),
        sa.Column("previous_score", sa.Float(), nullable=False),
        sa.Column("points_delta", sa.Float(), nullable=False),
        sa.Column("new_score", sa.Float(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entry_type IN ("
            "'INITIAL', 'EVENT_PENALTY', 'PATTERN_PENALTY', 'MANUAL_ADJUSTMENT', 'REVERSAL'"
            ")",
            name=op.f("ck_trip_score_ledger_entry_type"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_trip_score_ledger_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reverses_entry_id"],
            ["trip_score_ledger.id"],
            name=op.f("fk_trip_score_ledger_reverses_entry_id_trip_score_ledger"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rule_set_version_id"],
            ["rule_set_versions.id"],
            name=op.f("fk_trip_score_ledger_rule_set_version_id_rule_set_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["driving_events.id"],
            name=op.f("fk_trip_score_ledger_source_event_id_driving_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_score_ledger_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_score_ledger")),
    )
    op.create_index(
        op.f("ix_trip_score_ledger_source_event_id"),
        "trip_score_ledger",
        ["source_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trip_score_ledger_trip_id"), "trip_score_ledger", ["trip_id"], unique=False
    )
    op.create_index(
        "uq_trip_score_ledger_source_event",
        "trip_score_ledger",
        ["trip_id", "source_event_id"],
        unique=True,
        postgresql_where=sa.text("source_event_id IS NOT NULL AND entry_type = 'EVENT_PENALTY'"),
    )
    op.create_table(
        "trip_risk_history",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("previous_risk_level", sa.String(length=20), nullable=True),
        sa.Column("new_risk_level", sa.String(length=20), nullable=False),
        sa.Column("score_at_transition", sa.Float(), nullable=False),
        sa.Column("risk_band_id", sa.Uuid(), nullable=True),
        sa.Column("triggering_ledger_entry_id", sa.Uuid(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "new_risk_level IN ('LOW', 'MEDIUM', 'HIGH')",
            name=op.f("ck_trip_risk_history_new_risk_level"),
        ),
        sa.ForeignKeyConstraint(
            ["risk_band_id"],
            ["risk_bands.id"],
            name=op.f("fk_trip_risk_history_risk_band_id_risk_bands"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["triggering_ledger_entry_id"],
            ["trip_score_ledger.id"],
            name=op.f("fk_trip_risk_history_triggering_ledger_entry_id_trip_score_ledger"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_risk_history_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_risk_history")),
    )
    op.create_index(
        op.f("ix_trip_risk_history_trip_id"), "trip_risk_history", ["trip_id"], unique=False
    )
    op.create_table(
        "trip_score_states",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("initial_score", sa.Float(), server_default="100.0", nullable=False),
        sa.Column("current_score", sa.Float(), server_default="100.0", nullable=False),
        sa.Column("current_risk_level", sa.String(length=20), server_default="LOW", nullable=False),
        sa.Column("last_ledger_entry_id", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "current_risk_level IN ('LOW', 'MEDIUM', 'HIGH')",
            name=op.f("ck_trip_score_states_ck_trip_score_states_risk_level"),
        ),
        sa.CheckConstraint(
            "current_score >= 0.0 AND current_score <= 100.0",
            name=op.f("ck_trip_score_states_ck_trip_score_states_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["last_ledger_entry_id"],
            ["trip_score_ledger.id"],
            name=op.f("fk_trip_score_states_last_ledger_entry_id_trip_score_ledger"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_score_states_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_score_states")),
        sa.UniqueConstraint("trip_id", name="uq_trip_score_states_trip_id"),
    )
    op.create_index(
        op.f("ix_trip_score_states_current_risk_level"),
        "trip_score_states",
        ["current_risk_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trip_score_states_current_score"),
        "trip_score_states",
        ["current_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trip_score_states_trip_id"), "trip_score_states", ["trip_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_trips_rule_set_version_id_rule_set_versions"),
        "trips",
        "rule_set_versions",
        ["rule_set_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_trips_rule_set_version_id_rule_set_versions"), "trips", type_="foreignkey"
    )
    op.drop_index(op.f("ix_trip_score_states_trip_id"), table_name="trip_score_states")
    op.drop_index(op.f("ix_trip_score_states_current_score"), table_name="trip_score_states")
    op.drop_index(op.f("ix_trip_score_states_current_risk_level"), table_name="trip_score_states")
    op.drop_table("trip_score_states")
    op.drop_index(op.f("ix_trip_risk_history_trip_id"), table_name="trip_risk_history")
    op.drop_table("trip_risk_history")
    op.drop_index(
        "uq_trip_score_ledger_source_event",
        table_name="trip_score_ledger",
        postgresql_where=sa.text("source_event_id IS NOT NULL AND entry_type = 'EVENT_PENALTY'"),
    )
    op.drop_index(op.f("ix_trip_score_ledger_trip_id"), table_name="trip_score_ledger")
    op.drop_index(op.f("ix_trip_score_ledger_source_event_id"), table_name="trip_score_ledger")
    op.drop_table("trip_score_ledger")
    op.drop_index(op.f("ix_event_telemetry_links_telemetry_id"), table_name="event_telemetry_links")
    op.drop_index(op.f("ix_event_telemetry_links_event_id"), table_name="event_telemetry_links")
    op.drop_table("event_telemetry_links")
    op.drop_index(op.f("ix_event_detection_states_trip_id"), table_name="event_detection_states")
    op.drop_table("event_detection_states")
    op.drop_index(op.f("ix_driving_events_trip_id"), table_name="driving_events")
    op.drop_index(op.f("ix_driving_events_status"), table_name="driving_events")
    op.drop_index(op.f("ix_driving_events_started_at"), table_name="driving_events")
    op.drop_index(op.f("ix_driving_events_severity"), table_name="driving_events")
    op.drop_index(op.f("ix_driving_events_organization_id"), table_name="driving_events")
    op.drop_index(op.f("ix_driving_events_event_type"), table_name="driving_events")
    op.drop_table("driving_events")
    op.drop_index(op.f("ix_turning_rules_rule_set_version_id"), table_name="turning_rules")
    op.drop_table("turning_rules")
    op.drop_index(op.f("ix_risk_bands_rule_set_version_id"), table_name="risk_bands")
    op.drop_table("risk_bands")
    op.drop_index(op.f("ix_overspeed_rules_rule_set_version_id"), table_name="overspeed_rules")
    op.drop_table("overspeed_rules")
    op.drop_index(
        op.f("ix_event_severity_bands_rule_set_version_id"), table_name="event_severity_bands"
    )
    op.drop_table("event_severity_bands")
    op.drop_index(op.f("ix_event_penalties_rule_set_version_id"), table_name="event_penalties")
    op.drop_table("event_penalties")
    op.drop_index(
        op.f("ix_acceleration_rules_rule_set_version_id"), table_name="acceleration_rules"
    )
    op.drop_table("acceleration_rules")
    op.drop_index(op.f("ix_rule_set_versions_rule_set_id"), table_name="rule_set_versions")
    op.drop_table("rule_set_versions")
    op.drop_index(op.f("ix_rule_sets_organization_id"), table_name="rule_sets")
    op.drop_table("rule_sets")
    # ### end Alembic commands ###
