"""Add core fleet and trip tables

Revision ID: 949dfc0a8c86
Revises: '03703bcbb2ec'
Create Date: 2026-07-23 11:26:40.453158

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "949dfc0a8c86"
down_revision: str | None = "03703bcbb2ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization ownership foreign key",
        ),
        sa.Column(
            "device_code",
            sa.String(length=50),
            nullable=False,
            comment="Globally unique hardware/simulator device code",
        ),
        sa.Column(
            "display_name",
            sa.String(length=150),
            nullable=False,
            comment="Human-readable device display name",
        ),
        sa.Column(
            "device_type",
            sa.String(length=30),
            server_default="HARDWARE",
            nullable=False,
            comment="Device category type (HARDWARE or SIMULATOR)",
        ),
        sa.Column(
            "administrative_status",
            sa.String(length=20),
            server_default="ACTIVE",
            nullable=False,
            comment="Current administrative status",
        ),
        sa.Column(
            "firmware_version",
            sa.String(length=50),
            nullable=True,
            comment="Device firmware version string",
        ),
        sa.Column(
            "telemetry_schema_version",
            sa.String(length=20),
            server_default="v1",
            nullable=False,
            comment="Supported telemetry payload schema version",
        ),
        sa.Column(
            "api_key_hash",
            sa.String(length=255),
            nullable=True,
            comment="Hashed device API key credential",
        ),
        sa.Column(
            "last_credential_rotation_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of last API key rotation",
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "administrative_status IN ('ACTIVE', 'TESTING', 'DISABLED', 'RETIRED')",
            name=op.f("ck_devices_administrative_status"),
        ),
        sa.CheckConstraint(
            "device_type IN ('HARDWARE', 'SIMULATOR')", name=op.f("ck_devices_device_type")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_devices_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
    )
    op.create_index(op.f("ix_devices_device_code"), "devices", ["device_code"], unique=True)
    op.create_index(
        op.f("ix_devices_organization_id"), "devices", ["organization_id"], unique=False
    )
    op.create_table(
        "drivers",
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization ownership foreign key",
        ),
        sa.Column(
            "employee_code",
            sa.String(length=50),
            nullable=False,
            comment="Organization-scoped unique employee identifier",
        ),
        sa.Column("first_name", sa.String(length=100), nullable=False, comment="Driver first name"),
        sa.Column("last_name", sa.String(length=100), nullable=False, comment="Driver last name"),
        sa.Column("phone", sa.String(length=30), nullable=True, comment="Contact phone number"),
        sa.Column("email", sa.String(length=255), nullable=True, comment="Driver email address"),
        sa.Column(
            "license_number", sa.String(length=100), nullable=True, comment="Driving license number"
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="ACTIVE",
            nullable=False,
            comment="Current driver status (ACTIVE, INACTIVE, SUSPENDED)",
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')", name=op.f("ck_drivers_status")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_drivers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drivers")),
        sa.UniqueConstraint("organization_id", "employee_code", name="uq_drivers_employee_code"),
    )
    op.create_index(op.f("ix_drivers_employee_code"), "drivers", ["employee_code"], unique=False)
    op.create_index(
        op.f("ix_drivers_organization_id"), "drivers", ["organization_id"], unique=False
    )
    op.create_table(
        "vehicles",
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization ownership foreign key",
        ),
        sa.Column(
            "registration_number",
            sa.String(length=50),
            nullable=False,
            comment="Official vehicle license plate or registration number",
        ),
        sa.Column(
            "vehicle_code",
            sa.String(length=50),
            nullable=False,
            comment="Organization-scoped unique vehicle code",
        ),
        sa.Column(
            "make",
            sa.String(length=100),
            nullable=False,
            comment="Vehicle manufacturer make (e.g. Toyota)",
        ),
        sa.Column(
            "model", sa.String(length=100), nullable=False, comment="Vehicle model (e.g. Hilux)"
        ),
        sa.Column("manufacture_year", sa.Integer(), nullable=True, comment="Year of manufacture"),
        sa.Column(
            "vehicle_type",
            sa.String(length=50),
            server_default="SEDAN",
            nullable=False,
            comment="Vehicle classification type (e.g. SEDAN, TRUCK, VAN)",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="ACTIVE",
            nullable=False,
            comment="Current vehicle status",
        ),
        sa.Column(
            "default_speed_limit_kmh",
            sa.Float(),
            server_default="60.0",
            nullable=False,
            comment="Default speed limit in km/h for overspeed calculations",
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'RETIRED')",
            name=op.f("ck_vehicles_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vehicles_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint(
            "organization_id", "registration_number", name="uq_vehicles_registration_number"
        ),
        sa.UniqueConstraint("organization_id", "vehicle_code", name="uq_vehicles_vehicle_code"),
    )
    op.create_index(
        op.f("ix_vehicles_organization_id"), "vehicles", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_vehicles_registration_number"), "vehicles", ["registration_number"], unique=False
    )
    op.create_index(op.f("ix_vehicles_vehicle_code"), "vehicles", ["vehicle_code"], unique=False)
    op.create_table(
        "device_assignments",
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization ownership foreign key",
        ),
        sa.Column("device_id", sa.Uuid(), nullable=False, comment="Foreign key to assigned device"),
        sa.Column(
            "vehicle_id", sa.Uuid(), nullable=False, comment="Foreign key to assigned vehicle"
        ),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when assignment began",
        ),
        sa.Column(
            "unassigned_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when assignment ended (NULL for ACTIVE)",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="ACTIVE",
            nullable=False,
            comment="Assignment status (ACTIVE or ENDED)",
        ),
        sa.Column(
            "assigned_by_user_id",
            sa.Uuid(),
            nullable=True,
            comment="User who performed the assignment",
        ),
        sa.Column(
            "notes", sa.String(length=500), nullable=True, comment="Optional administrative notes"
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'ENDED')", name=op.f("ck_device_assignments_status")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"],
            ["users.id"],
            name=op.f("fk_device_assignments_assigned_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_assignments_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_device_assignments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_device_assignments_vehicle_id_vehicles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_assignments")),
    )
    op.create_index(
        op.f("ix_device_assignments_device_id"), "device_assignments", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_device_assignments_organization_id"),
        "device_assignments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_assignments_status"), "device_assignments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_device_assignments_vehicle_id"), "device_assignments", ["vehicle_id"], unique=False
    )
    op.create_index(
        "uq_device_assignments_active_device",
        "device_assignments",
        ["device_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_index(
        "uq_device_assignments_active_vehicle",
        "device_assignments",
        ["vehicle_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "trips",
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization ownership foreign key",
        ),
        sa.Column(
            "trip_code", sa.String(length=50), nullable=False, comment="Globally unique trip code"
        ),
        sa.Column("driver_id", sa.Uuid(), nullable=False, comment="Driver operating the trip"),
        sa.Column(
            "device_assignment_id",
            sa.Uuid(),
            nullable=False,
            comment="Device assignment (device+vehicle relationship) for this trip",
        ),
        sa.Column(
            "rule_set_version_id", sa.Uuid(), nullable=True, comment="Applied rule set version UUID"
        ),
        sa.Column(
            "started_by_user_id", sa.Uuid(), nullable=True, comment="User who started the trip"
        ),
        sa.Column("ended_by_user_id", sa.Uuid(), nullable=True, comment="User who ended the trip"),
        sa.Column(
            "trip_mode",
            sa.String(length=20),
            server_default="OFFICIAL",
            nullable=False,
            comment="Trip mode (OFFICIAL or TEST)",
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            server_default="ACTIVE",
            nullable=False,
            comment="Trip status (ACTIVE, COMPLETED, CANCELLED, FINALIZATION_FAILED)",
        ),
        sa.Column(
            "start_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when trip started",
        ),
        sa.Column(
            "end_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when trip ended",
        ),
        sa.Column(
            "applied_speed_limit_kmh",
            sa.Float(),
            server_default="60.0",
            nullable=False,
            comment="Speed limit applied to trip",
        ),
        sa.Column(
            "start_reason",
            sa.String(length=255),
            nullable=True,
            comment="Optional trip start justification",
        ),
        sa.Column(
            "end_reason",
            sa.String(length=255),
            nullable=True,
            comment="Optional trip end justification",
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'FINALIZING', 'COMPLETED', 'CANCELLED', 'FINALIZATION_FAILED')",
            name=op.f("ck_trips_status"),
        ),
        sa.CheckConstraint("trip_mode IN ('OFFICIAL', 'TEST')", name=op.f("ck_trips_trip_mode")),
        sa.ForeignKeyConstraint(
            ["device_assignment_id"],
            ["device_assignments.id"],
            name=op.f("fk_trips_device_assignment_id_device_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
            name=op.f("fk_trips_driver_id_drivers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ended_by_user_id"],
            ["users.id"],
            name=op.f("fk_trips_ended_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_trips_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["started_by_user_id"],
            ["users.id"],
            name=op.f("fk_trips_started_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
    )
    op.create_index(
        op.f("ix_trips_device_assignment_id"), "trips", ["device_assignment_id"], unique=False
    )
    op.create_index(op.f("ix_trips_driver_id"), "trips", ["driver_id"], unique=False)
    op.create_index(op.f("ix_trips_organization_id"), "trips", ["organization_id"], unique=False)
    op.create_index(op.f("ix_trips_status"), "trips", ["status"], unique=False)
    op.create_index(op.f("ix_trips_trip_code"), "trips", ["trip_code"], unique=True)
    op.create_index(
        "uq_trips_active_assignment",
        "trips",
        ["device_assignment_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('ACTIVE', 'FINALIZING')"),
    )
    op.create_index(
        "uq_trips_active_driver",
        "trips",
        ["driver_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('ACTIVE', 'FINALIZING')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_trips_active_driver",
        table_name="trips",
        postgresql_where=sa.text("status IN ('ACTIVE', 'FINALIZING')"),
    )
    op.drop_index(
        "uq_trips_active_assignment",
        table_name="trips",
        postgresql_where=sa.text("status IN ('ACTIVE', 'FINALIZING')"),
    )
    op.drop_index(op.f("ix_trips_trip_code"), table_name="trips")
    op.drop_index(op.f("ix_trips_status"), table_name="trips")
    op.drop_index(op.f("ix_trips_organization_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_driver_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_device_assignment_id"), table_name="trips")
    op.drop_table("trips")
    op.drop_index(
        "uq_device_assignments_active_vehicle",
        table_name="device_assignments",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(
        "uq_device_assignments_active_device",
        table_name="device_assignments",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(op.f("ix_device_assignments_vehicle_id"), table_name="device_assignments")
    op.drop_index(op.f("ix_device_assignments_status"), table_name="device_assignments")
    op.drop_index(op.f("ix_device_assignments_organization_id"), table_name="device_assignments")
    op.drop_index(op.f("ix_device_assignments_device_id"), table_name="device_assignments")
    op.drop_table("device_assignments")
    op.drop_index(op.f("ix_vehicles_vehicle_code"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_registration_number"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_organization_id"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_drivers_organization_id"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_employee_code"), table_name="drivers")
    op.drop_table("drivers")
    op.drop_index(op.f("ix_devices_organization_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_device_code"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
